### ISSUE TITLE
go mod vendor error

### ISSUE THREAD

**Issue by Funniest** [InsDrone/insdrone_protocol#1]
third_party/protobuf/examples 안의 *.go 파일들에 있는 import 중
```
pb "github.com/protocolbuffers/protobuf/examples/tutorial"
````
들을 전부 주석처리하면 문제 없이 vendor 생성 됨.

현재 위 URL이 404 상태임.

**Comment by gyungdal** [comment]
위 커밋에서 수정 완료 /close
